version: '3'
services:
  messaging-service:
    restart: always
    container_name: messaging-service
    build:
      context: ./backend/messaging-service
      dockerfile: Dockerfile
    expose:
      - "8080"
    networks:
      - app-network
  notifications-service:
    restart: always
    container_name: notifications-service
    build:
      context: ./backend/notifications-service
      dockerfile: Dockerfile
    expose:
      - "8080"
    networks:
      - app-network

  nginx:
    restart: always
    build:
      context: .
      dockerfile: nginx.dockerfile
    expose:
      - "80"
    ports:
      - "80:80"
    depends_on:
      - messaging-service
      - notifications-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
